spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/luckymoney
    url: jdbc:h2:~/luckymoney;IFEXISTS=TRUE?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
    open-in-view: false
logging.level:
  com.kakao.pay.luckymoney.api: info
  org.hibernate.SQL: info
#  org.hibernate.type: trace
